version: '3'
services:
    # Postgres database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
    # API Server
    api:
        depends_on:
            - postgres
        image: "nikitatuteja/simple_blog_api"
        build: .
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api